services:
  php-env:
    build: . #path to dockerfile
    volumes: 
      - ./src:/var/www/html 
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:latest
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1